name: end of day

on:
   schedule:
    - cron: '*/20 18 * * 5'
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - name: Build
        run: npm run build

      - name: eod actions
        uses: clickpesa/eod-actions@1.0.3
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_REVIEW_URL: ${{secrets.SLACK_WEBHOOK_REVIEW_URL}}
          TARGET_BRANCH: staging
          DESTINATION_BRANCH: main
          TEAM_LEAD_ID: ${{secrets.TEAM_LEAD_ID}}
          TECH_LEAD_ID: ${{secrets.TECH_LEAD_ID}}
          REPO_OWNER: bmsteven
          REPO_NAME: bump-version
