name: on merging to default branch

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: develop

      #  push changes to develop
      - name: set global attributes
        run: |
          git config --global user.email "bmsteve96@gmail.com"
          git config --global user.name "Benedict Steven"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
      - name: Build
        run: yarn

      - name: install jq
        run: yarn add jq
          
      - name: get version
        run: |
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"') 
          echo "::set-output name=PACKAGE_VERSION::$(cat ./package.json | jq '.version' | tr -d '"')"
          echo $PACKAGE_VERSION
        id: version

      - name: Build
        run: |
          yarn run all
        
      - name: test version
        run: echo ${{ steps.version.outputs.PACKAGE_VERSION }}

      - name: bump-version
        id: bump_version
        uses: ./
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          PACKAGE_VERSION: ${{ steps.version.outputs.PACKAGE_VERSION }}
          DELETE_BRANCH: false
          CHANGELOG_PATH: ./CHANGELOG.md
          PACKAGE_JSON_PATH: .package.json
      - name: test outputs
        run: |
          echo "The author was ${{ steps.bump_version.outputs.body }}"
          echo "The author was ${{ steps.bump_version.outputs.new_version }}"

      - name: update develop branch
        run: |
          git add package.json
          git add changelog.md
          git add action
          git commit -m "Skip CI"
          git push