name: on merging to default branch

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: develop

      #  push changes to develop
      - name: set global attributes
        run: |
          git config --global user.email "bmsteve96@gmail.com"
          git config --global user.name "Benedict Steven"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
      - name: Build
        run: npm install

      - name: install jq
        run: |
          npm install jq
          echo $(cat ./package.json | jq '.version' | tr -d '"')

      - name: Build
        run: npm run build

      - name: eod actions
        uses: ./
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          APP_NAME: Engineering-blog
          PACKAGE_VERSION: $(cat ./package.json | jq '.version' | tr -d '"')

      - name: update develop branch
        run: |
          git add package.json
          git add changelog.md
          git add action
          git commit -m "Skip CI"
          git push